name: Build Android APK

on:
  push:
    branches:
      - main  # Ou la branche de votre choix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20' # Spécifiez la version de Node.js qui correspond à votre projet

      - name: Install Ionic and Cordova
        run: npm install -g @ionic/cli @capacitor/core @capacitor/cli

      - name: Install npm dependencies
        run: npm install

      - name: capacitor-android-action
        uses: Narottam04/action-capacitor-android@v1.0.0

      - name: Build APK
        run: npm run build

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
