name: Build Android APK with Capacitor

on:
  push:
    branches:
      - main  # Ajustez selon la branche que vous souhaitez utiliser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  # AdoptOpenJDK est maintenant Eclipse Temurin

    - name: Install Node.js (Version 20)
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Ionic CLI
      run: npm install -g @ionic/cli

    - name: Install npm dependencies
      run: npm ci

    - name: Build Ionic App
      run: ionic build --prod

    - name: Install Capacitor CLI
      run: npm install @capacitor/cli @capacitor/core

    - name: Add Android Platform
      run: |
        npx cap add android

    - name: Build Android APK
      run: |
        npx cap sync android
        cd android
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
    - name: Send APK via POST request
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}  # Assurez-vous d'avoir ajouté ce secret dans GitHub
      run: |
        curl -X POST -H "Authorization: Bearer $BEARER_TOKEN" -F "file=@android/app/build/outputs/apk/debug/app-debug.apk" YOUR_ENDPOINT_URL

